@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho
Enum Bean
Class MakeCoffee
Enum Milk
Class Frother
Class Grinder
Class Boiler
Class ConcreteMediator
Interface Mediator
Abstract Class MachineComponent



MachineComponent --> Mediator
Mediator <|.. ConcreteMediator
Frother <-- ConcreteMediator
Grinder <-- ConcreteMediator
Boiler  <--ConcreteMediator


MachineComponent <|-- Grinder
MachineComponent <|-- Boiler
MachineComponent <|-- Frother

Abstract Class MachineComponent {
-mediator: Mediator
}

Interface Mediator{
+stopGrind():String
+stopBoil():String
+stopFroth():String
}

Class Grinder {
-Bean:bean
+grind():String
}

Enum Bean {
DARKROAST
LIGHTROAST
}

Enum Milk {
WHOLEMILK
SKIMMILK
}

Class Boiler {
+boil():String
}

Class Frother {
-Milk:milk
+froth():String
}


@enduml